# ****************************************
# appveyor.yml - Appveyor CI configuration
# ****************************************
environment:
  matrix:
    # We only have a pre-compiled PyQt5 for Python 3.5+, so only test on that.
    - PYTHON: "C:\\Python35"

install:
  # Add the correct Python to the path.
  - set PATH=%PYTHON%;%PYTHON%\Script;%PATH%
  # Install dependencies needed by the CI script.
  - python -m pip install -U -r tests\ci\requirements.txt
  # Use a python script to do all the heavy lifting.
  - python tests\ci\qutepart_appveyor.py install

# Use this to prevent Appveyor from running MSBuild. See https://www.appveyor.com/docs/appveyor-yml
# line 181.
build_script:
  - echo "Avoiding the MSBUILD step."

# See https://www.appveyor.com/docs/appveyor-yml line 215.
test_script:
  - python tests\ci\qutepart_appveyor.py test

# See https://www.appveyor.com/docs/build-cache.
cache:
  - \downloads
